### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by baidut** [baidut/ZhenqiangYING#1]
- [ ] 翻墙-作为一个程序猿应当具备的能力
- [ ] 经典程序猿面试题整理
  - [ ] 不使用变量实现strlen
  - [ ] 实现strcat.再对比strcat源码
- [ ] 定期撰写博客文章

**Comment by baidut** [comment]
博客撰写

计划每周撰写一篇质量较高的博文或译文，发布到csdn和github.io博客，目前的写作计划有

- [ ] 当大四的我重新修改大一时的C语言大作业
- [ ] 样本S语言编译器的构造
- [ ] 我与元胞自动机 不理解问题背景就死搬硬套 哲学家就餐、加热盘子
- [ ] 编程风格-反面例子-对事不对人

**Comment by baidut** [comment]
读书笔记
- [ ] 韩寒 我所理解的生活-第26回  春萍 我做到了

**Comment by baidut** [comment]
编程笔记
C细节：
char和int默认 signed
short等的大小总结
